var version = 1.2;
var execBtn = document.getElementById("execute");
var outputElm = document.getElementById('output');
var errorElm = document.getElementById('error');
var commandsElm = document.getElementById('commands');
var dbFileElm = document.getElementById('dbfile');
var savedbElm = document.getElementById('savedb');

// Start the worker in which sql.js will run
var worker = new Worker("www/js/worker.sql.js");
// alert(worker);
worker.onerror = error;

// Open a database
worker.postMessage({action:'open'});

// Connect to the HTML element we 'print' to
function print(text) {
  outputElm.innerHTML = text.replace(/\n/g, '<br>');
}
function error(e) {
  console.log(e);
  errorElm.style.height = '2em';
  errorElm.textContent = e.message;
}

function noerror() {
  errorElm.style.height = '0';
}

function disableActions(id) {
  $(id).addClass("disabledbutton");
  // console.log("actions disabled");
}
function enableActions(id) {
  $(id).removeClass("disabledbutton");
  // console.log("actions enabled");
}

// Run a command in the database
function execute(commands) {
  tic();
  worker.onmessage = function(event) {
    var results = event.data.results;
    toc("Executing SQL");

    tic();
    disableActions('#actions');
    outputElm.innerHTML = "";
    for (var i=0; i<results.length; i++) {
      outputElm.appendChild(tableCreate(results[i].columns, results[i].values));
      // dataTable.jq.js is a table filter and sort plugin
      $('table').dataTable( { "sDom": 'C&lt;"clear"&gt;lfrtip' });
    }
    toc("Displaying results");
    enableActions('#actions');
  }
  // try {
    // worker.postMessage({action:'exec',sql:commands});
  // }
  // catch(exception) {
    // worker.postMessage({action:'exec',sql:commands});
  // }
  worker.postMessage({action:'exec', sql:commands});
  outputElm.textContent = "Fetching results...";
}

// Create an HTML table
var tableCreate = function () {
  var timestampCol;
  function openTag(tagName, className) {
    return '<'+tagName+' class="'+className+'">'
  }
  function valconcat(vals, tagName) {
    if (vals.length === 0) return '';
    var n = 0
    var open = '<'+tagName+'>', close='</'+tagName+'>';
    // return open + vals.join(close + open) + close;
    var theRows='';
    switch (tagName) {
      case 'td':
        // console.log('tr vals='+vals);
        if (timestampCol) {
          // timestamp in tuScraper db is generated by python: timestamp=str(arrow.get(datetime.datetime.now()).timestamp)
          vals[timestampCol] = $.format.date(new Date(parseInt(vals[timestampCol]+'000')),'yyyy-MM-dd HH:mm:ss');
          return open + vals.join(close + open) + close;
        } else {
          return open + vals.join(close + open) + close;
        }
      break;
      case 'th':
        // console.log('th vals='+vals);
        for (i in vals) {
          // console.log('th vals['+i+']='+vals[i]);
          theRows+=openTag(tagName, vals[i].replace(/\W/g, '')) + vals[i] + close;
          if (vals[i] == 'timestamp') { timestampCol=i}
        }
      break;
      default:
        return open + vals.join(close + open) + close;
      break;
    }
    return theRows
  }
  return function (columns, values){
    var tbl  = document.createElement('table');
    // console.log('columns='+columns);
    var html = '<thead>' + valconcat(columns, 'th') + '</thead>';
    var rows = values.map(function(v){ return valconcat(v, 'td'); });
    html += '<tbody>' + valconcat(rows, 'tr') + '</tbody>';
    tbl.innerHTML = html;
    return tbl;
  }
}();

// Execute the commands when the button is clicked
function execEditorContents () {
  noerror();
  execute (editor.getValue() + ';');
}
execBtn.addEventListener("click", execEditorContents, true);

// Performance measurement functions
var tictime;
if (!window.performance || !performance.now) {window.performance = {now:Date.now}}
function tic () {tictime = performance.now()}
function toc(msg) {
  var dt = performance.now()-tictime;
  console.log((msg||'toc') + ": " + dt + "ms");
}

// TODO: implement codemirrot properly: https://github.com/angular-ui/ui-codemirror http://plnkr.co/edit/?p=preview
// Add syntax highlihjting to the textarea
var editor = CodeMirror.fromTextArea(commandsElm, {
    mode: 'text/x-mysql',
    viewportMargin: Infinity,
    indentWithTabs: true,
    smartIndent: true,
    lineNumbers: true,
    matchBrackets : true,
    autofocus: true,
    extraKeys: {
      "Ctrl-Enter": execEditorContents,
      "Ctrl-S": savedb,
    }
});

// Load a db from a file
dbFileElm.onchange = function() {
  var f = dbFileElm.files[0];
  var r = new FileReader();
  r.onload = function() {
    worker.onmessage = function () {
      toc("Loading database from file");
      // Show the schema of the loaded database
      editor.setValue("SELECT `name`, `sql`\n  FROM `sqlite_master`\n  WHERE type='table';");
      execEditorContents();
    };
    tic();
    try {
      console.log(r.result);
      worker.postMessage({action:'open',buffer:r.result}, [r.result]);
    }
    catch(exception) {
      worker.postMessage({action:'open',buffer:r.result});
    }
  }
  r.readAsArrayBuffer(f);
}

// Save the db to a file
function savedb () {
  worker.onmessage = function(event) {
    toc("Exporting the database");
    var arraybuff = event.data.buffer;
    var blob = new Blob([arraybuff]);
    var a = document.createElement("a");
    a.href = window.URL.createObjectURL(blob);
    a.download = "sql.db";
    a.onclick = function() {
      setTimeout(function() {
        window.URL.revokeObjectURL(a.href);
      }, 1500);
    };
    a.click();
  };
  tic();
  worker.postMessage({action:'export'});
}
savedbElm.addEventListener("click", savedb, true);

// TODO: DONE! progress bar http://jsfiddle.net/GvdSy/ https://jsfiddle.net/zinoui/sx61fgm3/
function updateProgress(evt) {
  if (evt.lengthComputable) {
    var percentComplete = evt.loaded / evt.total;
    console.log("updateProgress "+percentComplete);
    updateProgressBar('update',percentComplete);
  } else {
    console.log("updateProgress unable to compute");
  }
}
function transferComplete(evt) { console.log("The transfer is complete"); }
function transferFailed(evt) { console.log("transferFailed"); }
function transferCanceled(evt) { console.log("transferCanceled"); }
function loadEnd(evt) { console.log("The transfer finished"); }

function execBtnLoadXhr2LoadFile(url) {
  var xhr = new XMLHttpRequest();
  updateProgressBar('init',0);
  xhr.addEventListener("progress", updateProgress);
  xhr.addEventListener("load", transferComplete);
  xhr.addEventListener("error", transferFailed);
  xhr.addEventListener("abort", transferCanceled);
  xhr.addEventListener("loadend", loadEnd);

  tic();
  disableActions('#actions');
  xhr.open('GET', url, true);
  xhr.responseType = 'arraybuffer';
  xhr.onload = function() {
    console.log(this.response); // THIS is the ArrayBuffer we want for the worker postMessage buffer !
    worker.onmessage = function () {
      toc("Loading database from url: "+url);
      // Show the schema of the loaded database
      editor.setValue("SELECT `name`, `sql`\n  FROM `sqlite_master`\n  WHERE type='table';");
      execEditorContents();
    };
    try {
      worker.postMessage({action:'open',buffer:this.response}, [this.response]);
    }
    catch(exception) {
      worker.postMessage({action:'open',buffer:this.response});
    }
  }
  xhr.send();
}
var execBtnLoadDbXhr0 = document.getElementById('loadDbXhr0');
var execBtnLoadDbXhrFull = document.getElementById('loadDbXhrFull');
// TODO: BUG: for some reason these addEventListener are executed on load of the page, why?
// execBtnLoadDbXhr0.addEventListener("click", execBtnLoadXhr2LoadFile('tuScraper.0.sqlite3'));
// execBtnLoadDbXhrFull.addEventListener("click", execBtnLoadXhr2LoadFile('tuScraper.sqlite3'));
execBtnLoadDbXhr0.onclick = function(e) { execBtnLoadXhr2LoadFile('tuScraper.0.sqlite3'); }
execBtnLoadDbXhrFull.onclick = function(e) { execBtnLoadXhr2LoadFile('tuScraper.sqlite3'); }

function setEditorSql(buttonId) {
  var sql;
  switch (buttonId) {
    case 'classes':
      sql = "SELECT * from classes LIMIT 10;";
      break;
    case 'fields':
      sql = "SELECT * from fields LIMIT 10;";
      break;
    case 'history':
      sql = "SELECT * from history LIMIT 10;";
      break;
    case 'sql_mySurvey':
      sql = "SELECT * from perso_fall2017;";
      break;
    case 'sql_ITEC':
      sql = "SELECT * from  ITEC_fall2017;";
      break;
    case 'sql_timestamp':
      sql = "select timestamp,title,SeatsTaken,(SeatsOpen-waitlisttotal) from history,classes \
      where history.classnumber = '2792' \
      order by timestamp asc \
      ;";
      break;
    default:
      sql = "select name,sql from sqlite_master \
      where type in ('table','view');";
      break;
  }
  // console.log('buttonId='+buttonId+' sql='+sql);
  editor.setValue(sql);
}

// old school:
/* var execBtnInjectSql = document.getElementsByClassName('injectSql');
for (var i = 0; i < execBtnInjectSql.length; i += 1) {
  execBtnInjectSql[i].onclick = function(e) {
    setEditorSql(this.id);
    execute (editor.getValue() + ';');
  };
}*/
// jquery school:
$(".injectSql").each(function(){
  this.onclick = function(e) {
    setEditorSql(this.id);
    execute (editor.getValue() + ';');
  };
});

// TODO: add my own class switcher here:
// TODO: disable upload buttons for 4s after success
function updateProgressBar(state,percentComplete) {
  switch (state) {
    case 'init':
      $('.progressBar').removeClass('hide');
      break;
    default:
      $('.progressBar').css({ width: percentComplete * 100 + '%' });
      if (percentComplete === 1) { $('.progressBar').addClass('hide').css({ width: 0 }); }
      break;
  }
}

// TODO: generate the hiddenTooltip divs based on setEditorSql to the DOM, from here
